project_id = "afxptjzzctiowrqqcyzh"

[api]
enabled = true
port = 54321

[edge_runtime]
enabled = true
policy = "per_worker"
deno_version = 2

[functions.dining-ingest]
verify_jwt = true

[functions.campus-activity-sync]
verify_jwt = true

[functions.campus-data]
verify_jwt = false
