export const diningPreview = {
  calories: 1840,
  calorieGoal: 2400,
  protein: 138,
  proteinGoal: 160,
  carbs: 192,
  carbGoal: 247,
  fats: 58,
  fatGoal: 65,
  halls: [
    {
      id: 'bruin-plate',
      name: 'Bruin Plate',
      imageSource: require('../Ucla dining hall logos /bruin plate.png'),
      fitPercent: 94,
      hours: {
        breakfast: '7:00 AM - 9:00 AM',
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'epicuria-covel',
      name: 'Epicuria at Covel',
      imageSource: require('../Ucla dining hall logos /epicuria at covel.png'),
      fitPercent: 92,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'de-neve',
      name: 'De Neve',
      imageSource: require('../Ucla dining hall logos /De Neve.png'),
      fitPercent: 88,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '10:00 PM - 12:00 AM',
      },
    },
    {
      id: 'feast-rieber',
      name: 'Feast at Rieber',
      imageSource: require('../Ucla dining hall logos /Feast.png'),
      fitPercent: 90,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 11:00 PM',
      },
    },
    {
      id: 'bruin-cafe',
      name: 'Bruin Cafe',
      imageSource: require('../Ucla dining hall logos /bruin cafe.png'),
      fitPercent: 81,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'cafe-1919',
      name: 'Cafe 1919',
      imageSource: require('../Ucla dining hall logos /cafe 1919.png'),
      fitPercent: 76,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 10:00 PM',
      },
    },
    {
      id: 'study-hedrick',
      name: 'The Study',
      imageSource: require('../Ucla dining hall logos /the study.png'),
      fitPercent: 84,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 12:00 AM',
      },
    },
    {
      id: 'the-drey',
      name: 'The Drey',
      imageSource: require('../Ucla dining hall logos /drey.png'),
      fitPercent: 79,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'rendezvous',
      name: 'Rendezvous',
      imageSource: require('../Ucla dining hall logos /rende.png'),
      fitPercent: 86,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'bruin-bowl',
      name: 'Bruin Bowl',
      imageSource: require('../Ucla dining hall logos /Bruin Bowl.png'),
      fitPercent: 91,
      hours: {
        breakfast: null,
        lunch: null,
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'epicuria-ackerman',
      name: 'Epicuria at Ackerman',
      imageSource: require('../Ucla dining hall logos /epic at akermann.png'),
      fitPercent: 83,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
  ],
  recentMeals: [
    { id: 'm-1', title: 'Protein oats', meta: 'Breakfast', calories: 420 },
    { id: 'm-2', title: 'Harissa chicken bowl', meta: 'Lunch', calories: 610 },
    { id: 'm-3', title: 'Greek yogurt', meta: 'Snack', calories: 190 },
  ],
} as const;

export const gymPreview = {
  weekStrip: [
    { id: 'mon', label: 'M', active: true },
    { id: 'tue', label: 'T', active: true },
    { id: 'wed', label: 'W', active: true },
    { id: 'thu', label: 'T', active: true, highlighted: true },
    { id: 'fri', label: 'F' },
    { id: 'sat', label: 'S' },
    { id: 'sun', label: 'S' },
  ],
  capacities: [
    {
      id: 'wooden',
      name: 'Wooden Center',
      hours: '6:00 AM - 11:00 PM',
      load: 0.3,
      percent: 30,
      tone: 'blue' as const,
    },
    {
      id: 'bfit',
      name: 'BFit Gym',
      hours: '6:00 AM - 10:00 PM',
      load: 0.75,
      percent: 75,
      tone: 'gold' as const,
    },
  ],
  templates: ['Push', 'Legs', 'Pull', 'Upper'],
  exercises: [
    {
      id: 'ex-1',
      name: 'Bulgarian Split Squat',
      sets: '4 sets',
      repRange: '8-10 reps',
      previous: '95 lbs',
      current: '105',
      reps: '10',
      active: true,
    },
    {
      id: 'ex-2',
      name: 'Barbell Back Squat',
      sets: '4 sets',
      repRange: '6-8 reps',
      previous: '205 lbs',
      current: '225',
      reps: '8',
      active: false,
    },
    {
      id: 'ex-3',
      name: 'Leg Press',
      sets: '3 sets',
      repRange: '12 reps',
      previous: '360 lbs',
      current: '405',
      reps: '12',
      active: false,
    },
  ],
  totalVolume: 12450,
  weeklyGoalProgress: 0.78,
} as const;

export const profilePreview = {
  summary: [
    { id: 'workouts', label: 'Workouts', value: '5' },
    { id: 'calories', label: 'Avg calories', value: '2,210' },
    { id: 'protein', label: 'Avg protein', value: '154g' },
  ],
  prs: [
    { id: 'pr-1', title: 'Bench Press', value: '225 lbs', note: 'Latest PR' },
    { id: 'pr-2', title: 'Trap Bar Deadlift', value: '375 lbs', note: 'All-time best' },
  ],
  goals: {
    calories: '2,400 kcal target',
    protein: '160g daily target',
  },
  templates: [
    { id: 't-1', title: 'Push Day', detail: 'Chest, shoulders, triceps' },
    { id: 't-2', title: 'Leg Day', detail: 'Squat, hinge, calves' },
    { id: 't-3', title: 'Upper Pull', detail: 'Back, rear delts, biceps' },
  ],
  diningPreferences: ['Epicuria', 'Bruin Plate', 'High protein'],
} as const;
