export const diningPreview = {
  calories: 1840,
  calorieGoal: 2400,
  protein: 138,
  proteinGoal: 160,
  carbs: 192,
  carbGoal: 247,
  fats: 58,
  fatGoal: 65,
  halls: [
    {
      id: 'bruin-plate',
      name: 'Bruin Plate',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/BP_Cookbook_Spreads3858-bruin-plate.jpg',
      fitPercent: 94,
      hours: {
        breakfast: '7:00 AM - 9:00 AM',
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'epicuria-covel',
      name: 'Epicuria at Covel',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/Antipasto-Platter-2100x600-ai.jpg',
      fitPercent: 92,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'de-neve',
      name: 'De Neve Dining',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/5DM45162-de-neve-hero-alt.jpg',
      fitPercent: 88,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '10:00 PM - 12:00 AM',
      },
    },
    {
      id: 'feast-rieber',
      name: 'Feast at Rieber',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/Antipasto-Platter-2100x600-ai.jpg',
      fitPercent: 90,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 11:00 PM',
      },
    },
    {
      id: 'bruin-cafe',
      name: 'Bruin Cafe',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/Sandwich_RoastBeef_MG_1663-3000x800-1-scaled.jpg',
      fitPercent: 81,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'cafe-1919',
      name: 'Cafe 1919',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/05/Il-Carnivora_MG_9177-2100x600v2-1024x293.jpg',
      fitPercent: 76,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 10:00 PM',
      },
    },
    {
      id: 'study-hedrick',
      name: 'The Study at Hedrick',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/The-Study-Day-2-219_MV-hero.jpg',
      fitPercent: 84,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 12:00 AM',
      },
    },
    {
      id: 'the-drey',
      name: 'The Drey',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/the-drey-hero-Beef-Pho_MG_1174.jpg',
      fitPercent: 79,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'rendezvous',
      name: 'Rendezvous',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/BBQ-Chicken-Quesadilla_MG_1035-rendezvous-alt-hero-3-1.jpg',
      fitPercent: 86,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'bruin-bowl',
      name: 'Bruin Bowl',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/04/bruin-bowl-hero-ai-Mediterranean_8R9A6378.jpg',
      fitPercent: 91,
      hours: {
        breakfast: null,
        lunch: null,
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'epicuria-ackerman',
      name: 'Epicuria at Ackerman',
      imageUrl: 'https://dining.ucla.edu/wp-content/uploads/2025/03/Epicuria-at-Ackerman-Shoot-135-2100x800-1.jpg',
      fitPercent: 83,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
  ],
  recentMeals: [
    { id: 'm-1', title: 'Protein oats', meta: 'Breakfast', calories: 420 },
    { id: 'm-2', title: 'Harissa chicken bowl', meta: 'Lunch', calories: 610 },
    { id: 'm-3', title: 'Greek yogurt', meta: 'Snack', calories: 190 },
  ],
} as const;

export const gymPreview = {
  weekStrip: [
    { id: 'mon', label: 'M', active: true },
    { id: 'tue', label: 'T', active: true },
    { id: 'wed', label: 'W', active: true },
    { id: 'thu', label: 'T', active: true, highlighted: true },
    { id: 'fri', label: 'F' },
    { id: 'sat', label: 'S' },
    { id: 'sun', label: 'S' },
  ],
  capacities: [
    {
      id: 'wooden',
      name: 'Wooden Center',
      status: 'Open until 11PM',
      load: 0.82,
      percent: 82,
      tone: 'blue' as const,
    },
    {
      id: 'bfit',
      name: 'BFit Gym',
      status: 'Busy right now',
      load: 0.94,
      percent: 94,
      tone: 'gold' as const,
    },
  ],
  templates: ['Push Day', 'Leg Day', 'Pull', 'Upper'],
  exercises: [
    {
      id: 'ex-1',
      name: 'Bulgarian Split Squat',
      sets: '4 sets',
      repRange: '8-10 reps',
      previous: '95 lbs',
      current: '105',
      reps: '10',
      active: true,
    },
    {
      id: 'ex-2',
      name: 'Barbell Back Squat',
      sets: '4 sets',
      repRange: '6-8 reps',
      previous: '205 lbs',
      current: '225',
      reps: '8',
      active: false,
    },
    {
      id: 'ex-3',
      name: 'Leg Press',
      sets: '3 sets',
      repRange: '12 reps',
      previous: '360 lbs',
      current: '405',
      reps: '12',
      active: false,
    },
  ],
  totalVolume: 12450,
  weeklyGoalProgress: 0.78,
} as const;

export const profilePreview = {
  summary: [
    { id: 'workouts', label: 'Workouts', value: '5' },
    { id: 'calories', label: 'Avg calories', value: '2,210' },
    { id: 'protein', label: 'Avg protein', value: '154g' },
  ],
  prs: [
    { id: 'pr-1', title: 'Bench Press', value: '225 lbs', note: 'Latest PR' },
    { id: 'pr-2', title: 'Trap Bar Deadlift', value: '375 lbs', note: 'All-time best' },
  ],
  goals: {
    calories: '2,400 kcal target',
    protein: '160g daily target',
  },
  templates: [
    { id: 't-1', title: 'Push Day', detail: 'Chest, shoulders, triceps' },
    { id: 't-2', title: 'Leg Day', detail: 'Squat, hinge, calves' },
    { id: 't-3', title: 'Upper Pull', detail: 'Back, rear delts, biceps' },
  ],
  diningPreferences: ['Epicuria', 'Bruin Plate', 'High protein'],
} as const;
