export const diningPreview = {
  calories: 1840,
  calorieGoal: 2400,
  protein: 138,
  proteinGoal: 160,
  carbs: 192,
  carbGoal: 247,
  fats: 58,
  fatGoal: 65,
  halls: [
    {
      id: 'bruin-plate',
      name: 'Bruin Plate',
      imageSource: require('../Ucla dining hall logos transparent/bruin plate.png'),
      fitPercent: 94,
      hours: {
        breakfast: '7:00 AM - 9:00 AM',
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'epicuria-covel',
      name: 'Epicuria at Covel',
      imageSource: require('../Ucla dining hall logos transparent/epicuria at covel.png'),
      fitPercent: 92,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'de-neve',
      name: 'De Neve',
      imageSource: require('../Ucla dining hall logos transparent/De Neve.png'),
      fitPercent: 88,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '10:00 PM - 12:00 AM',
      },
    },
    {
      id: 'feast-rieber',
      name: 'Feast at Rieber',
      imageSource: require('../Ucla dining hall logos transparent/Feast.png'),
      fitPercent: 90,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 2:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 11:00 PM',
      },
    },
    {
      id: 'bruin-cafe',
      name: 'Bruin Cafe',
      imageSource: require('../Ucla dining hall logos transparent/bruin cafe.png'),
      fitPercent: 81,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'cafe-1919',
      name: 'Cafe 1919',
      imageSource: require('../Ucla dining hall logos transparent/cafe 1919.png'),
      fitPercent: 76,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 10:00 PM',
      },
    },
    {
      id: 'study-hedrick',
      name: 'The Study',
      imageSource: require('../Ucla dining hall logos transparent/the study.png'),
      fitPercent: 84,
      hours: {
        breakfast: '7:00 AM - 10:00 AM',
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: '9:00 PM - 12:00 AM',
      },
    },
    {
      id: 'the-drey',
      name: 'The Drey',
      imageSource: require('../Ucla dining hall logos transparent/drey.png'),
      fitPercent: 79,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'rendezvous',
      name: 'Rendezvous',
      imageSource: require('../Ucla dining hall logos transparent/rende.png'),
      fitPercent: 86,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 3:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'bruin-bowl',
      name: 'Bruin Bowl',
      imageSource: require('../Ucla dining hall logos transparent/Bruin Bowl.png'),
      fitPercent: 91,
      hours: {
        breakfast: null,
        lunch: null,
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
    {
      id: 'epicuria-ackerman',
      name: 'Epicuria at Ackerman',
      imageSource: require('../Ucla dining hall logos transparent/epic at akermann.png'),
      fitPercent: 83,
      hours: {
        breakfast: null,
        lunch: '11:00 AM - 4:00 PM',
        dinner: '5:00 PM - 9:00 PM',
        lateNight: null,
      },
    },
  ],
  recentMeals: [
    { id: 'm-1', title: 'Protein oats', meta: 'Breakfast', calories: 420 },
    { id: 'm-2', title: 'Harissa chicken bowl', meta: 'Lunch', calories: 610 },
    { id: 'm-3', title: 'Greek yogurt', meta: 'Snack', calories: 190 },
  ],
} as const;

export const gymPreview = {
  weekStrip: [
    { id: 'mon', label: 'M', active: true },
    { id: 'tue', label: 'T', active: true },
    { id: 'wed', label: 'W', active: true },
    { id: 'thu', label: 'T', active: true, highlighted: true },
    { id: 'fri', label: 'F' },
    { id: 'sat', label: 'S' },
    { id: 'sun', label: 'S' },
  ],
  capacities: [
    {
      id: 'wooden',
      name: 'Wooden Center',
      hours: '6:00 AM - 11:00 PM',
      load: 0.3,
      percent: 30,
      zones: [
        { name: 'Pardee Gym', count: 16, capacity: 50, percent: 32 },
        { name: 'Cardio Zone', count: 17, capacity: 60, percent: 28 },
        { name: 'Free Weight Zone', count: 18, capacity: 65, percent: 28 },
        { name: 'Functional Training Zone', count: 7, capacity: 40, percent: 18 },
      ],
      zoneName: 'Pardee Gym',
      tone: 'blue' as const,
    },
    {
      id: 'bfit',
      name: 'BFit Gym',
      hours: '6:00 AM - 10:00 PM',
      load: 0.75,
      percent: 75,
      zones: [
        { name: 'Cardio Zones 1&2', count: 18, capacity: 100, percent: 18 },
        { name: 'Free Weight & Squat Zones', count: 22, capacity: 80, percent: 28 },
        { name: 'Selectorized Zone', count: 14, capacity: 50, percent: 28 },
      ],
      zoneName: 'Free Weight & Squat Zones',
      tone: 'gold' as const,
    },
  ],
  templates: ['Push', 'Legs', 'Pull', 'Upper'],
  exercises: [
    {
      id: 'ex-1',
      name: 'Bulgarian Split Squat',
      sets: '4 sets',
      repRange: '8-10 reps',
      previous: '95 lbs',
      current: '105',
      reps: '10',
      active: true,
    },
    {
      id: 'ex-2',
      name: 'Barbell Back Squat',
      sets: '4 sets',
      repRange: '6-8 reps',
      previous: '205 lbs',
      current: '225',
      reps: '8',
      active: false,
    },
    {
      id: 'ex-3',
      name: 'Leg Press',
      sets: '3 sets',
      repRange: '12 reps',
      previous: '360 lbs',
      current: '405',
      reps: '12',
      active: false,
    },
  ],
  totalVolume: 12450,
  weeklyGoalProgress: 0.78,
} as const;

export const profilePreview = {
  goals: {
    calories: '2,400 kcal',
    protein: '160g',
    fats: '65g',
    carbs: '247g',
    workouts: '4 / week',
  },
  summary: [
    { id: 'workouts', label: 'Workouts', value: '5' },
    { id: 'calories', label: 'Avg calories', value: '2,210' },
  ],
  weeks: [
    {
      id: 'week-1',
      startDate: '2026-03-23',
      label: 'Mar 23 - Mar 29',
      days: [
        { id: 'w1-mon', day: 'M', date: '23', workout: true, nutrition: true },
        { id: 'w1-tue', day: 'T', date: '24', workout: false, nutrition: true },
        { id: 'w1-wed', day: 'W', date: '25', workout: true, nutrition: false },
        { id: 'w1-thu', day: 'T', date: '26', workout: false, nutrition: true },
        { id: 'w1-fri', day: 'F', date: '27', workout: true, nutrition: true },
        { id: 'w1-sat', day: 'S', date: '28', workout: false, nutrition: false },
        { id: 'w1-sun', day: 'S', date: '29', workout: true, nutrition: true },
      ],
    },
    {
      id: 'week-2',
      startDate: '2026-03-30',
      label: 'Mar 30 - Apr 5',
      days: [
        { id: 'w2-mon', day: 'M', date: '30', workout: true, nutrition: true },
        { id: 'w2-tue', day: 'T', date: '31', workout: true, nutrition: true },
        { id: 'w2-wed', day: 'W', date: '1', workout: false, nutrition: true },
        { id: 'w2-thu', day: 'T', date: '2', workout: true, nutrition: false },
        { id: 'w2-fri', day: 'F', date: '3', workout: false, nutrition: false },
        { id: 'w2-sat', day: 'S', date: '4', workout: false, nutrition: true },
        { id: 'w2-sun', day: 'S', date: '5', workout: true, nutrition: true },
      ],
    },
    {
      id: 'week-3',
      startDate: '2026-04-06',
      label: 'Apr 6 - Apr 12',
      days: [
        { id: 'w3-mon', day: 'M', date: '6', workout: true, nutrition: true },
        { id: 'w3-tue', day: 'T', date: '7', workout: false, nutrition: true },
        { id: 'w3-wed', day: 'W', date: '8', workout: true, nutrition: true },
        { id: 'w3-thu', day: 'T', date: '9', workout: false, nutrition: false },
        { id: 'w3-fri', day: 'F', date: '10', workout: false, nutrition: false },
        { id: 'w3-sat', day: 'S', date: '11', workout: false, nutrition: false },
        { id: 'w3-sun', day: 'S', date: '12', workout: false, nutrition: false },
      ],
    },
  ],
  achievements: [
    { id: 'a-1', title: 'First workout logged', detail: 'Started your first session in Bruin Gains', date: 'Apr 8', icon: 'barbell-outline', tone: 'workout' },
    { id: 'a-2', title: 'Protein streak', detail: 'Hit your protein goal 5 days in a row', date: 'Apr 7', icon: 'flame-outline', tone: 'nutrition' },
    { id: 'a-3', title: 'Hall hopper', detail: 'Tried 3 different UCLA dining halls this week', date: 'Apr 5', icon: 'restaurant-outline', tone: 'nutrition' },
    { id: 'a-4', title: 'Survived finals week nutrition', detail: 'Stayed on plan during a heavy school week', date: 'Mar 30', icon: 'school-outline', tone: 'nutrition' },
  ],
} as const;
